#pragma once

#include "BackGround.h"
#include "Camera.h"
#include "WorldObject.h"
#include "Stageone_Terrain.h"
#include "TriggerObject.h"
#include "DecalObject.h"
#include "Instance_WorldObject.h"
#include "Camera.h"
#include "CWorldParticle.h"
#include "GuiObject.h"
///////////플레이어/////////
#include "Player.h"
#include "PlayerAim.h"
#include "FSM_Idle.h"
#include "FSM_Move.h"
#include "FSM_Jump.h"
#include "FSM_Crouch.h"
#include "FSM_Hand.h"
#include "Player_Arm.h"
#include "Player_LeftHand.h"
#include "Player_RightHand.h"
#include "FSM_LeftHand.h"
#include "FSM_RightHand.h"

/////////////////보스//////////////
#include "Boss_Teacher.h"
#include "Teacher_FSM.h"
#include "FSM_Teacher_IDLE.h"
#include "FSM_Teacher_Move.h"
#include "FSM_Teacher_Spawn.h"
#include "FSM_Teacher_Dead.h"
#include "Cat.h"
#include "Cat_FSM.h"
#include "Cat_Fog.h"
#include "FSM_Cat_Spawn.h"